# BOUT_TOP = $(HOME)/Documents/DTU/BOUT-dev
SOURCEC		= intercomm_monitor.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.hxx)
MODULE_DIR  = ../..
SUB_NAME	= IntercommMonitor
TARGET		= sub

BOUT_TOP = $(HOME)/BOUT-dev
#BOUT_TOP = $(MODULE_DIR)/../BOUT-dev
include $(BOUT_TOP)/make.config
