# BOUT_TOP = $(HOME)/Documents/DTU/BOUT-dev
SOURCEC		= HeselParameters.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.hxx)
MODULE_DIR  = ../HESEL-Common
SUB_NAME	= HeselParameters
TARGET		= sub

BOUT_TOP = $(MY_HOME)/BOUT-dev
include $(BOUT_TOP)/make.config
